- hosts: all
  handlers:
  - name: Retart ntpd
    service:
      name: ntpd
      state: restarted
      enabled: yes

  tasks:
  - name: Install ntpd
    yum: 
      name: ntp
      state: latest
    notify: Restart ntpd

  - name: Reconfigure time servers
    lineinfile:
      path: /etc/ntp.conf
      regexp: '^server.*iburst$'
      line: 'server pool.ntp.org iburst'
    notify: Restart ntpd
